update geo.geo set name='Makgadikgadi Pan (Desert)',rank=1,aka='',wikikey='Makgadikgadi_Pan' where gid=136;
delete from geo.geo where gid = 137;
delete from geo.geo where gid = 138;
delete from geo.geo where gid = 139;
delete from geo.geo where gid = 140;
update geo.geo set name='Salar de Uyuni Desert',rank=2,aka='Salar de Tunupa',wikikey='Salar_de_Uyuni' where gid=425;
update geo.geo set name='Wahiba Sands Desert',rank=1,aka='Sharqiya Sands',wikikey='Sharqiya_Sands' where gid=426;
update geo.geo set name='Danakil Desert',rank=1,aka='',wikikey='Danakil_Desert' where gid=427;
update geo.geo set name='Negev Desert',rank=1,aka='',wikikey='Negev' where gid=428;
update geo.geo set name='Chalbi Desert',rank=2,aka='',wikikey='Chalbi_Desert' where gid=429;
update geo.geo set name='Eastern Desert',rank=2,aka='Red Sea Hills',wikikey='Eastern_Desert' where gid=430;
delete from geo.geo where gid = 431;
delete from geo.geo where gid = 432;
delete from geo.geo where gid = 433;
update geo.geo set name='Erg Iguidi (Desert)',rank=2,aka='',wikikey='Erg_Iguidi' where gid=434;
update geo.geo set name='Strzelecki Desert',rank=1,aka='',wikikey='Strzelecki_Desert' where gid=435;
update geo.geo set name='Simpson Desert',rank=1,aka='',wikikey='Simpson_Desert' where gid=436;
update geo.geo set name='Tanami Desert',rank=1,aka='',wikikey='Tanami_Desert' where gid=437;
update geo.geo set name='Rigestan Desert',rank=1,aka='Registan, Sistan Desert',wikikey='Registan_Desert' where gid=438;
update geo.geo set name='Margo Desert',rank=1,aka='Dasht-e Margo, Dasht-e Mārgow, Dasht-e Margoh',wikikey='Dasht-e_Margo' where gid=439;
update geo.geo set name='Kavir Desert',rank=1,aka='Dasht-e Kavir, Kavir-e Namak, Great Salt Desert',wikikey='Dasht-e_Kavir' where gid=440;
update geo.geo set name='An Nafud Desert',rank=2,aka='An Nafud, Al-Nefud, The Nefud',wikikey='An_Nafud' where gid=441;
delete from geo.geo where gid = 442;
update geo.geo set name='Idhän Murzuq (Desert)',rank=2,aka='Murzuq Desert, Idehan Murzuq, Murzaq, Murzuk, Marzuq, Murzak',wikikey='Murzuq_Desert' where gid=591;
delete from geo.geo where gid = 592;
update geo.geo set name='Ténéré (Desert)',rank=2,aka='Tenere',wikikey='Ténéré' where gid=593;
delete from geo.geo where gid = 594;
delete from geo.geo where gid = 595;
update geo.geo set name='Sarïr Kalanshiyu ar Ramli al Kabi (Desert)',rank=2,aka='Calansho Sand Sea, Calanscio, Calancio, Kalansho, Kalanslio',wikikey='Calanshio_Sand_Sea' where gid=596;
update geo.geo set name='Grand Erg Oriental (Desert)',rank=2,aka='Great Eastern Sand Sea',wikikey='Grand_Erg_Oriental' where gid=597;
update geo.geo set name='Grand Erg Occidental (Desert)',rank=2,aka='Western Sand Sea',wikikey='Grand_Erg_Occidental' where gid=598;
update geo.geo set name='Erg Chech (Desert)',rank=2,aka='',wikikey='Erg_Chech' where gid=599;
update geo.geo set name='El Djouf (Desert)',rank=2,aka='',wikikey='El_Djouf' where gid=600;
update geo.geo set name='Chihuahuan Desert',rank=1,aka='',wikikey='Chihuahuan_Desert' where gid=601;
update geo.geo set name='Sonoran Desert',rank=1,aka='',wikikey='Sonoran_Desert' where gid=602;
update geo.geo set name='Great Salt Lake Desert',rank=1,aka='',wikikey='Great_Basin_Desert' where gid=603;
update geo.geo set name='Gibson Desert',rank=1,aka='',wikikey='Gibson_Desert' where gid=604;
update geo.geo set name='Mu Us Desert',rank=2,aka='Maowusu Desert',wikikey='Mu_Us_Desert' where gid=605;
update geo.geo set name='Taklimakan Desert',rank=1,aka='Taklamakan',wikikey='Taklamakan_Desert' where gid=606;
update geo.geo set name='Lut Desert',rank=1,aka='Dasht-e Lut',wikikey='Dasht-e_Lut' where gid=607;
update geo.geo set name='Namib Desert',rank=1,aka='Namibe (Portuguese)',wikikey='Namib' where gid=795;
update geo.geo set name='Western Desert',rank=2,aka='',wikikey='Western_Desert_(Egypt)' where gid=796;
update geo.geo set name='Nubian Desert',rank=2,aka='',wikikey='Nubian_Desert' where gid=797;
update geo.geo set name='Great Sandy Desert',rank=1,aka='',wikikey='Great_Sandy_Desert' where gid=798;
update geo.geo set name='Libyan Desert',rank=2,aka='',wikikey='Libyan_Desert' where gid=799;
update geo.geo set name='Great Victoria Desert',rank=1,aka='',wikikey='Great_Victoria_Desert' where gid=800;
update geo.geo set name='Thar Desert',rank=1,aka='Great Indian Desert',wikikey='Thar_Desert' where gid=801;
update geo.geo set name='Syrian Desert',rank=2,aka='North Arabian Desert, Jordanian steppe, Badiya',wikikey='Syrian_Desert' where gid=802;
update geo.geo set name='Garagum Desert',rank=1,aka='Karakum, Kara-Kum,Gara-Gum',wikikey='Karakum_Desert' where gid=803;
update geo.geo set name='Qizilqum Desert',rank=1,aka='Kyzylkum Desert',wikikey='Kyzylkum_Desert' where gid=804;
update geo.geo set name='Atacama Desert',rank=1,aka='Desierto de Atacama (Spanish)',wikikey='Atacama_Desert' where gid=805;
update geo.geo set name='Betpaqdala Desert',rank=1,aka='Betpak-Dala',wikikey='Betpak-Dala' where gid=879;
delete from geo.geo where gid = 880;
update geo.geo set name='Rub'' al Khali Desert',rank=2,aka='',wikikey='Rub%27_al_Khali' where gid=881;
update geo.geo set name='Caatingas Desert',rank=1,aka='',wikikey='Caatinga' where gid=882;
update geo.geo set name='Kalahari Desert',rank=1,aka='',wikikey='Kalahari_Desert' where gid=883;
update geo.geo set name='Gobi Desert',rank=1,aka='',wikikey='Gobi_Desert' where gid=921;
update geo.geo set name='Sahara Desert',rank=1,aka='',wikikey='Sahara' where gid=922;
insert into geo.geo (name,rank,aka,wikikey) values ('Arabian Desert',1,'','Arabian_Desert');
insert into geo.geo (name,rank,aka,wikikey) values ('Great Basin Desert',1,'','Great_Salt_Lake_Desert');
insert into geo.geo (name,rank,aka,wikikey) values ('Great Australian Desert',1,'outback','Deserts_of_Australia');
insert into geo.geo (name,rank,aka,wikikey) values ('Ordos Desert',1,'','Ordos_Desert');
insert into geo.geo (name,rank,aka,wikikey) values ('Kubuqi Desert',2,'','Kubuqi_Desert');
